<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.100" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="MonoTorrent" Version="3.0.2" />
    <PackageVersion Include="Plugin.LocalNotification" Version="14.1.1" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="Xamarin.Google.Android.Play.App.Update" Version="2.1.0.20" />
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.14.0.6" />
    <PackageVersion Include="Xamarin.AndroidX.Activity.Ktx" Version="1.13.0.1" />
    <PackageVersion Include="Xamarin.AndroidX.Collection.Ktx" Version="1.6.0.1" />
    <PackageVersion Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.9.0" />
    <PackageVersion Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.11.0.1" />
    <PackageVersion Include="Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx" Version="2.11.0.1" />
    <PackageVersion Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx" Version="2.11.0.1" />
    <PackageVersion Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx.Android" Version="2.11.0.1" />
    <PackageVersion Include="Xamarin.AndroidX.Lifecycle.ViewModel.Ktx" Version="2.11.0.1" />
    <PackageVersion Include="Xamarin.AndroidX.SavedState.SavedState.Ktx" Version="1.5.0.1" />
  </ItemGroup>
</Project>
